<template>
	<div class="main-container">
		<router-view></router-view>
		<!-- Navbar section -->
		<HeaderSoftware />

		<div id="home" />
		
		<!-- hero section -->
		<HeroSoftware />
	
		<div class="feature-icon-list-area section-space--pt_120 "  id="visualize" >
            <div class="container">
                <div class="section-title-wrapper text-left section-space--mb_100">
                    <h2 class="section-title font-weight--light mb-30 text-center wow move-up">Your data in its natural form... dive in!</h2>

					<ul class="visualize green-check-list section-space--mb_50">
                        <li class="list-item vr"> <p id="space"> syGlass software allows you to view your data in its actual 3D or 4D (over time) form through virtual reality.</p> </li>
                        <li class="list-item data"><p id="space"> We specialize in presenting very large data sets that are generated by microscopes, patient, and industrial scanners. </p></li>
                        <li class="list-item tool"><p id="space"> Use our tools to quantify your data with enhanced precision, or import your results for rapid correction in VR. </p></li>
                        <li class="list-item mission"> <p id="space"> Our mission is to provide tools for investigators to understand complex data sets completely and communicate their findings efficiently. </p></li>
                    </ul> 

					<iframe class="mainvid" src="https://www.youtube.com/embed/kSHqWX0cKbs?autoplay=1&controls=1&modestbranding&mute=1&loop=1&playlist=kSHqWX0cKbs"/>

				</div>
			</div>
		</div>

		
		
		<TestimonialOne />


		<!-- tab content section -->
        <div class="tabs-wrapper startup-tab section-space--mt_60 section-space--pt_120" id="analyze">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-title-wrapper text-center section-space--mb_60 wow move-up">
                            <h2 class="section-title font-weight--bold mb-15">Increased throughput and accuracy with syGlass</h2>
                        </div>
                    </div>
                </div>
                <!-- tab components -->
               <TabOne />
            </div>
        </div>
		
		<TabTwo_Communicate id="communicate"/>
	
		<!-- download View call to action -->
        <CtaThree  id="view"/>

		<!-- syGlass View Projects -->
		<!-- PortfolioGridCaption -->
		

		
		<!-- FAQ -->
        <!-- accordion section >
        <div class="software-accordion-wrapper section-space--pt_120 " id="faq">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-title-wrapper text-center section-space--mb_60">
                            <h2 class="section-title font-weight--light mb-10 wow move-up">Frequently Asked Questions</h2>
                            <span class="section-text wow move-up">It’s our pleasure to answer any questions you have</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="faq-wrapper">
                            <!-- accordion component -->
                            <!--Accordion />
                        </div>
                    </div>
					<div class="col">
						<div class="peatures_image-wrap section-space--mb_40">
								<div class="image text-center wow move-up">
									<img class="img-fluid" src="../assets/img/syglass/graphs.png" alt="contact thumb">
								</div>
						</div>
					</div>
                </div>
            </div>
        </div-->

				<!--TestimonialOne /-->

		<!-- tab content section -->
       
                <!-- tab components -->
        <Recs id="requirements"/>


		        <!-- business analytics start -->
        <div class="feature-icon-list-area section-space--pt_120 "  id="about" >
            <div class="container">
                <div class="section-title-wrapper text-center">
                    <h2 class="section-title font-weight--light mb-30 wow move-up">Created by Scientists, for Scientists</h2>
					<p id="aboutSpace"> 
Launched by an NIH Innovation Grant, syGlass grew out of neuroscience and computer vision laboratories at West Virginia University. 
syGlass was initially designed for the university’s neuroscience researchers, overcoming a major problem they faced: complex and large datasets viewing neurons and their connections across scales of resolution.
Inundated with requests by other scientists to use our software, we worked to affordably commercialize syGlass and share our inventive features for laboratories around the world. 
When you purchase a license, you gain the collaborative syGlass team, readily available to assist with your work and always advancing analysis tools so that you can focus on obtaining the data and processing the results.
</p>
				</div>
			</div>
		</div>

		


		<ContactForm />

		<!-- footer section -->
        <FooterMain />

        <!-- offcanvas search component -->
        <OffcanvasSearchBox />



	</div>
</template>

<script>
	import HeaderSoftware from "../components/HeaderSoftware";
	import HeroSoftware from "../components/HeroSoftware";
	import TabTwo_Communicate from "../components/TabTwo_Communicate";
	import CtaThree from "../components/CtaThree";
	import CtaOne from "../components/CtaOne";
	import FooterMain from "../components/FooterMain";
	import OffcanvasSearchBox from "../components/OffcanvasSearchBox";
	import ContactForm from "../components/ContactForm";
	import TabOne from "../components/TabOne";
	import TestimonialOne from "../components/TestimonialOne"
	import Recs from "../components/Recs"
	import Visualize from "../components/Visualize"

	export default {
		data() {
				return {
						
						swiperOption: {
								speed: 1500,
								loop: true,
								effect: 'fade',
								autoplay: false,
								spaceBetween : 10,
								navigation: {
										nextEl: '.swiper-button-next',
										prevEl: '.swiper-button-prev'
								},
						},
						swiperImages: {
								speed: 1500,
								loop: true,
								effect: 'fade',
								autoplay: true,
								slidesPerView: 'auto',
								loopedSlides: 3,
								spaceBetween : 10,
								navigation: {
										nextEl: '.swiper-button-next',
										prevEl: '.swiper-button-prev'
								},
						}
				};
		},
		name: "app",
		components: {
			HeaderSoftware,
			HeroSoftware,
			TabOne,
			TabTwo_Communicate,
			CtaThree,
			CtaOne,
            FooterMain,
            OffcanvasSearchBox	,
			ContactForm,
			TestimonialOne,
			Recs, 
			Visualize
		}
	};
</script>

<style lang="scss" scoped>
    @import '../assets/scss/variabls.scss';
    @import '../assets/scss/elements/hero-software.scss';
	
	#space {
		padding-left: 20px;
	}

	.y {
        color: rgb(255, 255, 158);
		color: #44A3F2;
	}

    .list-item.vr {
        &::before {
            content: '\f6ea';
			font-size: 25px;
            font-weight: 400;
        }
	}
	
	.list-item.tool {
        &::before {
            content: '\f7d9';
            font-weight: 400;
			font-size: 25px;
        }
	}

	.list-item.data {
        &::before {
            content: '\f080';
			font-size: 25px;
			/*content: '\f643';*/
            font-weight: 400;
        }
	}

	.list-item.mission {
        &::before {
            content: '\f0eb';
            font-weight: 350;
			font-size: 30px;
        }
	}


</style>
