<template>
      <div class="feature-icon-list-area section-space--pt_120 "  id="visualize" >
            <div class="container">
                <div class="section-title-wrapper text-center section-space--mb_100">
                    <h2 class="section-title font-weight--light mb-30 wow move-up">Your data in its natural form... dive in!</h2>
					<p> syGlass software allows you to view your data in its actual 3D or 4D (over time) form through virtual reality. </br> We specialize in presenting very large data sets generated by modern imaging techniques. </br>
						
						Use our tools to quantify your data with enhanced precision, or import results for rapid correction in VR. </br>
						
						Our mission is to help scientists explore their data more creatively, and to understand and communicate their findings more efficiently.</p>

					<iframe class="mainvid" src="https://www.youtube.com/embed/kSHqWX0cKbs?autoplay=1&controls=1&modestbranding&mute=1&loop=1&playlist=kSHqWX0cKbs"/>


				</div>
			</div>
		</div>

</template>

<script>
	import Visualize from "../components/Visualize"

	export default {
		data() {
				return {
						
						swiperOption: {
								speed: 1500,
								loop: true,
								effect: 'fade',
								autoplay: false,
								spaceBetween : 10,
								navigation: {
										nextEl: '.swiper-button-next',
										prevEl: '.swiper-button-prev'
								},
						},
						swiperImages: {
								speed: 1500,
								loop: true,
								effect: 'fade',
								autoplay: true,
								slidesPerView: 'auto',
								loopedSlides: 3,
								spaceBetween : 10,
								navigation: {
										nextEl: '.swiper-button-next',
										prevEl: '.swiper-button-prev'
								},
						}
				};
		},
		name: "Visualize",
		components: {
			Visualize
		}
	};
</script>